apiVersion: v1
kind: Service
metadata:
  name: opiniones-lb
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 5000
  selector:
  #  Para todo los pots que tengan la etiqueta io.kompose.network/opt-default: "true"
    io.kompose.service: opiniones