apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: opiniones
  name: opiniones
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: opiniones
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: opiniones
    spec:
      containers:
        - env:
            - name: URI_MONGODB
              value: mongodb://root:example@mongo:27017/
          image: opiniones-rest:2.0
          name: opiniones
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
