apiVersion: v1
kind: Service
metadata:
  name: mongo-express-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
  #  Para todo los pots que tengan la etiqueta io.kompose.network/opt-default: "true"
    io.kompose.service: mongo-express