apiVersion: v1
kind: Service
metadata:
  name: pasarela-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090 
  selector:
  #  Para todo los pots que tengan la etiqueta io.kompose.network/opt-default: "true"
    io.kompose.service: pasarela