apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: pasarela
  name: pasarela
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pasarela
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: pasarela
    spec:
      containers:
        - env:
            - name: zuul.routes.opiniones.path
              value: /opiniones/**
            - name: zuul.routes.opiniones.url
              value: http://opiniones:5002/api/opiniones
            - name: zuul.routes.restaurantes.path
              value: /restaurantes/**
            - name: zuul.routes.restaurantes.url
              value: http://restaurantes:8080/api/restaurantes
          image: pasarela:2.0
          name: pasarela
          ports:
            - containerPort: 8090
          resources: {}
      restartPolicy: Always
status: {}
