apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: restaurantes
  name: restaurantes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: restaurantes
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: restaurantes
    spec:
      containers:
        - image: restaurantes:2.0
          name: restaurantes
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
